### ISSUE TITLE
Storybook deployment on Netlify

### ISSUE THREAD

**Issue by GuillaumeCasbas** [GuillaumeCasbas/grumbling-bear#3]
Setup the Storybook deployment on Netlify by CircleCI.

# Rules:
- The tests must pass
- After the NPM publishing

# Todo
- [ ] Storybook build command
- [ ] Setup custom domain DNS rules on Netlify
- [ ] Add deployment rules
